name: TestNotify

on:
  workflow_dispatch: {}
  push:
    branches:
      - main

env:
  NPM_TOKEN_BI_CHART: ${{secrets.NPM_TOKEN}}
  THREE_MICRO_APP: ${{secrets.THREE_MICRO_APP}}

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      # 签出您的存储库$GITHUB_WORKSPACE，以便您的工作流可以访问它。
      - uses: actions/checkout@v3
      # 安装 pnpm 包管理器
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      # 使用特定版本的 node.js 设置 GitHub Actions 工作流程
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'pnpm'
      - run: pnpm i --frozen-lockfile
      - run: pnpm run notify-test
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
